# Generated by Django 4.0.5 on 2022-07-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_rename_project_title_academic_project_project_title2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic_project',
            old_name='project_title2',
            new_name='project_title',
        ),
    ]
