# Generated by Django 4.0.5 on 2022-07-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_rename_project_title2_academic_project_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_resumes',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
