# Generated by Django 4.0.5 on 2022-07-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_my_resumes_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_resumes',
            name='resume',
            field=models.FileField(upload_to='resumes'),
        ),
    ]
