# Generated by Django 4.0.5 on 2022-07-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_alter_my_resumes_resume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_resumes',
            new_name='published_resumes',
        ),
    ]
